name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Echo Hello World
              run: echo "Hello World"

            - name: Try to echo the secret
              run: echo ${{ secrets.TEST_SECRET }}
            
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.7

            - name: Run Script
              run: |
                python3 scripts/python/secret_extract.py '${{ secrets.TEST_SECRET }}'